### ISSUE TITLE
Having trouble setting arabic unicode values on text fields

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/pdfparser#14]
If I try to set an arabic or chinese unicode value on a text field, it seems to work, but if I open the pdf, the arabic characters are not rendered and the field appears to be empty (or the arabic characters appear to be missing)

**Comment by bengolder** [comment]
Here is a collection of snippets and links relating to unicode in iText:
https://gist.github.com/bengolder/529ee55addad590b9f95e74d78ebe9a9

If I understand these correctly, there are several factors at play that affect the display of unicode glyphs.
- `AcroForm.setNeedAppearances(true)` passes responsibility for rendering glyphs to the PDF reading software, which would then presumably look for fonts through the local OS.
- `TextField.setExtensionFont()` and `TextField.setSubstitutionFonts()` let you add fonts for rendering glyphs not found in the base font, and will embed a subset of the substitute fonts. It is unclear to me if this embeds the entirety of the base font, or if it just embeds a subset for all glyphs used in the PDF.
- `BaseFont.EMBEDDED` and `BaseFont.NOT_EMBEDDED` are options that can be set during `BaseFont` creation to determine whether the font should be embedded in the document. Embedding a font, particularly a Unicode font, can greatly increase the file size of the PDF, but would guarantee that all the glyphs could be displayed, even if the PDF text is edited later on in another environment.

**Comment by brennv** [comment]
https://github.com/itext/itextpdf/blob/develop/itext/src/main/java/com/itextpdf/text/pdf/TrueTypeFont.java
seems to be another core dependency for unicode support.

**Comment by bengolder** [comment]
This is now resolved with https://github.com/codeforamerica/pdfparser/commit/af1646fcedc3c305cee44adb17385d6a815f266e

UNICODE IS NOW LIVE!!! 🎉 🎉 

<img width="485" alt="screen shot 2016-06-08 at 9 13 07 pm" src="https://cloud.githubusercontent.com/assets/451510/15918662/f2ca821a-2dbd-11e6-9338-0e77ffc4f393.png">

[arabic.pdf](https://github.com/codeforamerica/pdfparser/files/306103/arabic.pdf)
