### ISSUE TITLE
use OpenPDF

### ISSUE THREAD

**Issue by brennv** [codeforamerica/pdfparser#23]
See https://github.com/rtfarte/OpenPDF

Pull requested openpdf jars into libs/openpdf https://github.com/codeforamerica/pdfparser/pull/22

**Comment by brennv** [comment]
I swapped references from itext to openpdf in another branch https://github.com/codeforamerica/pdfparser/pull/24

**Comment by brennv** [comment]
Results from `mvn clean package`

```
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.592 s
[INFO] Finished at: 2016-06-08T22:56:37-07:00
[INFO] Final Memory: 16M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile 
(default-compile) on project pdfparser: Compilation failure: Compilation failure:
[ERROR] projects/cfa/pdfparser/src/main/java/converters/PdfToJsonConverter.java:[152,61] cannot find symbol
[ERROR] symbol:   class FieldPosition
[ERROR] location: class converters.PdfToJsonConverter
[ERROR] projects/cfa/pdfparser/src/main/java/converters/PdfToJsonConverter.java:[91,14] cannot find symbol
[ERROR] symbol:   class FieldPosition
[ERROR] location: class converters.PdfToJsonConverter
[ERROR] projects/cfa/pdfparser/src/main/java/converters/PdfToJsonConverter.java:[157,14] cannot find symbol
[ERROR] symbol:   class FieldPosition
[ERROR] location: class converters.PdfToJsonConverter
[ERROR] projects/cfa/pdfparser/src/main/java/PdfParser.java:[98,37] cannot find symbol
[ERROR] symbol:   method addDocument(com.lowagie.text.pdf.PdfReader)
[ERROR] location: variable copy of type com.lowagie.text.pdf.PdfCopy
```

**Comment by brennv** [comment]
AcroFields OpenPDF 1.0 vs itext 5.1.0 http://www.mergely.com/Ky4EtswZ/

**Comment by ghost** [comment]
Thanks for the interest in OpenPDF, I see that you have made several improvements to OpenPDF in your own forked branch. If you think that any of these improvements are generally useful for others as well, perhaps you could create a pull-request to get them included in rtfarge/OpenPDF?  I would happily review a pull-request from you about this.

**Comment by ghost** [comment]
By the way, we also need help to create a public release of OpenPDF to the public maven repo.

**Comment by bengolder** [comment]
I made some progress on switching to Open PDF from iText. We now have successful builds, and should be using the OpenPDF API correctly. But the code will not yet run. My best guess is that we need to change how we configure Open PDF as a dependency in `pom.xml` but I'm not sure how.

I suspect that once OpenPDF publishes to the maven central repository, it might be easier to configure it as a dependency. For anyone interested in helping them publish, please refer to this issue: https://github.com/rtfarte/OpenPDF/issues/3

**Comment by bengolder** [comment]
Here is the current error we are getting when we try to run the built `pdfparser.jar`:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/lowagie/text/DocumentException
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.DocumentException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more
make: *** [field_data] Error 1
```

**Comment by bengolder** [comment]
I made [a fork of OpenPDF](https://github.com/bengolder/OpenPDF) that I was able to successfully [publish on Maven Central](https://github.com/rtfarte/OpenPDF/issues/3). Now we no longer have to include dependencies in this repo. We can simply list them in our pom.xml like this:

``` xml
  <!-- Open PDF & associated dependencies -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.54</version>
        </dependency>
        <dependency>
            <groupId>com.github.bengolder</groupId>
            <artifactId>openpdf</artifactId>
            <version>1.0</version>
        </dependency>
```

**Comment by bengolder** [comment]
In #26 all the commands are running successfully with openpdf except for `concat_pdfs` which seems to be producing an invalid PDF file.
